TEST_DATA = {
    'crop': {'new': '/KzLuf69nu6UIBIKuBRiIneiaQe8=/0x0:200x200/150x150/my.domain.com/some/image/url.jpg',
             'old': '/ZiXWugE8r7PzJS4S3udk5qsLs4Hsb93Us-Qkd-85l5moJF1_LLBXRkVDOCo4srAVYqO4mSHWiHMQBtZSQBjNlQ==/my.domain.com/some/image/url.jpg',
             'opts': {'center': [100, 100],
                      'height': 150,
                      'original_height': 200,
                      'original_width': 300,
                      'width': 150}},
    'crop_missing_height': {'new': '/0XL5BmMi3vlJQfw6aGOVW-M1vVI=/10x0:90x100/80x0/my.domain.com/some/image/url.jpg',
                            'old': '/Zk0HkgT-8jbK0bWjtpOGwxEKrTNeOA_5MRTDhoQlywoWoVckf9glCqzApbOeN2McOpkhW_MQiUlmjucWzhl1fg==/my.domain.com/some/image/url.jpg',
                            'opts': {'center': [50, 50],
                                     'original_height': 100,
                                     'original_width': 100,
                                     'width': 80}},
    'crop_missing_width': {'new': '/02BNIIJ9NYNV9Q03JHPtlP0DIDg=/0x10:100x90/0x80/my.domain.com/some/image/url.jpg',
                           'old': '/frEjkK519Uv2s7aFQfXN0BEKrTNeOA_5MRTDhoQlywoWoVckf9glCqzApbOeN2McOpkhW_MQiUlmjucWzhl1fg==/my.domain.com/some/image/url.jpg',
                           'opts': {'center': [50, 50],
                                    'height': 80,
                                    'original_height': 100,
                                    'original_width': 100}},
    'crop_negative_height': {'new': '/-8IhWGEeXaY1uv945i9EHLVjwuk=/0x10:100x90/50x-40/my.domain.com/some/image/url.jpg',
                             'old': '/Q3YDfGoj2igpf7Ye5s3OKq8vRU93OTR7-A37uYiE7Rd6hyFeUS2tZjXAdh07hQL6cT-zg0msEoFQZ9X1EjcXbg==/my.domain.com/some/image/url.jpg',
                             'opts': {'center': [50, 50],
                                      'height': -40,
                                      'original_height': 100,
                                      'original_width': 100,
                                      'width': 50}},
    'crop_negative_height_width': {'new': '/lfjGLTTEaW_Rcvc1q0ZhfYup2jg=/0x10:100x90/-50x-40/my.domain.com/some/image/url.jpg',
                                   'old': '/jA-8MOomMPhRq-azgxSDJmjS3EktUfguFVj7Yk9SCJioJF1_LLBXRkVDOCo4srAVYqO4mSHWiHMQBtZSQBjNlQ==/my.domain.com/some/image/url.jpg',
                                   'opts': {'center': [50, 50],
                                            'height': -40,
                                            'original_height': 100,
                                            'original_width': 100,
                                            'width': -50}},
    'crop_negative_width': {'new': '/IuRNPlFlpTVol45bDkOm2PGvneo=/0x10:100x90/-50x40/my.domain.com/some/image/url.jpg',
                            'old': '/jA-8MOomMPhRq-azgxSDJq8vRU93OTR7-A37uYiE7Rd6hyFeUS2tZjXAdh07hQL6cT-zg0msEoFQZ9X1EjcXbg==/my.domain.com/some/image/url.jpg',
                            'opts': {'center': [50, 50],
                                     'height': 40,
                                     'original_height': 100,
                                     'original_width': 100,
                                     'width': -50}},
    'empty_filters': {'new': '/964rCTkAEDtvjy_a572k7kRa0SU=/my.domain.com/some/image/url.jpg',
                      'old': '/CDxCJT0ZmRlFAnX4cSpdkvVM9cB4m8sk2UUHOaYGy6_lXXGXm2Ux9PV6we7enK02/my.domain.com/some/image/url.jpg',
                      'opts': {'filters': []}},
    'flip': {'new': '/rlI4clPR-p-PR2QAxj5ZWiTfvH4=/-0x0/my.domain.com/some/image/url.jpg',
             'old': '/FZ6d-sbMJEV_gDsYYRaLmPsF3EeBv9I6N3AJ8G_-uLoyYXgziZYmUblajiMVwtiE/my.domain.com/some/image/url.jpg',
             'opts': {'flip': True}},
    'flip_flop': {'new': '/FnMxpQMmxiMpdG219Dsj8pD_4Xc=/-0x-0/my.domain.com/some/image/url.jpg',
                  'old': '/jgRJfRtVQMoxq55pSa65HIKzqfXvHPpTEZzYBP1EbLnynvgyyWmcybNEl-5VCPan/my.domain.com/some/image/url.jpg',
                  'opts': {'flip': True, 'flop': True}},
    'flip_width': {'new': '/ccr2PoSYcTEGL4_Wzt4u3wWVRKU=/-300x0/my.domain.com/some/image/url.jpg',
                   'old': '/AKkCWwcgYu9j67JQFZbZkRcoa-W5wb51TvHL1nOolGmfPqFbRzcq_o3Sh5Ip3piq/my.domain.com/some/image/url.jpg',
                   'opts': {'flip': True, 'width': 300}},
    'flop': {'new': '/-4dmGj-TwIEqTAL9_9yEqUM8cks=/0x-0/my.domain.com/some/image/url.jpg',
             'old': '/2KOUdu3BSStONZ0ORzY4TvsF3EeBv9I6N3AJ8G_-uLoyYXgziZYmUblajiMVwtiE/my.domain.com/some/image/url.jpg',
             'opts': {'flop': True}},
    'flop_height': {'new': '/R5K91tkyNgXO65F6E0txgA6C9lY=/0x-300/my.domain.com/some/image/url.jpg',
                    'old': '/n-0G_4TqFQNi8Mjxo47Kihcoa-W5wb51TvHL1nOolGmfPqFbRzcq_o3Sh5Ip3piq/my.domain.com/some/image/url.jpg',
                    'opts': {'flop': True, 'height': 300}},
    'halign_center': {'new': '/964rCTkAEDtvjy_a572k7kRa0SU=/my.domain.com/some/image/url.jpg',
                      'old': '/CDxCJT0ZmRlFAnX4cSpdkvVM9cB4m8sk2UUHOaYGy6_lXXGXm2Ux9PV6we7enK02/my.domain.com/some/image/url.jpg',
                      'opts': {'halign': 'center'}},
    'halign_left': {'new': '/GTJE3wUt3sURik0O9Nae8sfI928=/left/my.domain.com/some/image/url.jpg',
                    'old': '/mrxpsD4VH8Kg4_tuKj81RPsF3EeBv9I6N3AJ8G_-uLoyYXgziZYmUblajiMVwtiE/my.domain.com/some/image/url.jpg',
                    'opts': {'halign': 'left'}},
    'halign_valign_smart': {'new': '/KS6mVuzlGE3hJ75n3JUonfGgSFM=/left/top/smart/my.domain.com/some/image/url.jpg',
                            'old': '/9T25xpnR1glkY6rUwtqe9YRsYt933npxRp6FA2qKWw07sGap3zmi3qkD8jw2tIqf/my.domain.com/some/image/url.jpg',
                            'opts': {'halign': 'left',
                                     'smart': True,
                                     'valign': 'top'}},
    'horizontal_crop_with_actual_center': {'new': '/JLH65vJTu6d-cXBmqe5hYoSD4ho=/10x0:90x100/40x50/my.domain.com/some/image/url.jpg',
                                           'old': '/BbIn4e2Hf5tN7Mn4uG09eEkKXlHMWVG2Hvgmx9qpSB0S6eY7AokKR8MxWv-SG1MITsAJ-HZkU5sksimly3NCpA==/my.domain.com/some/image/url.jpg',
                                           'opts': {'center': [50, 50],
                                                    'height': 50,
                                                    'original_height': 100,
                                                    'original_width': 100,
                                                    'width': 40}},
    'horizontal_crop_with_left_center': {'new': '/NEtCYehaISE7qR3zFj15CxnZoCs=/20x0:100x100/40x50/my.domain.com/some/image/url.jpg',
                                         'old': '/WlbGMMtTfNZ-t_8FEX6Yn4ZdfSa5iKy2M0M33DltZ3B6hyFeUS2tZjXAdh07hQL6cT-zg0msEoFQZ9X1EjcXbg==/my.domain.com/some/image/url.jpg',
                                         'opts': {'center': [100, 50],
                                                  'height': 50,
                                                  'original_height': 100,
                                                  'original_width': 100,
                                                  'width': 40}},
    'meta': {'new': '/WvIJFDJDePgIl5hZcLgtrzIPxfY=/meta/my.domain.com/some/image/url.jpg',
             'old': '/hKUPSrzTap_b1y0y2A94m_sF3EeBv9I6N3AJ8G_-uLoyYXgziZYmUblajiMVwtiE/my.domain.com/some/image/url.jpg',
             'opts': {'meta': True}},
    'no_crop_when_missing_orig_height': {'new': '/veYlY0msKmemAaXpeav2kCNftmU=/50x40/my.domain.com/some/image/url.jpg',
                                         'old': '/x2OIJliJQ-cEk_PdQGBbzoKzqfXvHPpTEZzYBP1EbLnynvgyyWmcybNEl-5VCPan/my.domain.com/some/image/url.jpg',
                                         'opts': {'center': [50, 50],
                                                  'height': 40,
                                                  'original_width': 100,
                                                  'width': 50}},
    'no_crop_when_missing_orig_weight': {'new': '/veYlY0msKmemAaXpeav2kCNftmU=/50x40/my.domain.com/some/image/url.jpg',
                                         'old': '/x2OIJliJQ-cEk_PdQGBbzoKzqfXvHPpTEZzYBP1EbLnynvgyyWmcybNEl-5VCPan/my.domain.com/some/image/url.jpg',
                                         'opts': {'center': [50, 50],
                                                  'height': 40,
                                                  'original_height': 100,
                                                  'width': 50}},
    'no_crop_when_missing_width_height': {'new': '/964rCTkAEDtvjy_a572k7kRa0SU=/my.domain.com/some/image/url.jpg',
                                          'old': '/CDxCJT0ZmRlFAnX4cSpdkvVM9cB4m8sk2UUHOaYGy6_lXXGXm2Ux9PV6we7enK02/my.domain.com/some/image/url.jpg',
                                          'opts': {'center': [50, 50],
                                                   'original_height': 100,
                                                   'original_width': 100}},
    'no_crop_when_not_needed': {'new': '/trIjfr513nkGkCpKXK6qgox2jPA=/50x50/my.domain.com/some/image/url.jpg',
                                'old': '/KuA2QY1ZP0qXIrbQu_M8S4KzqfXvHPpTEZzYBP1EbLnynvgyyWmcybNEl-5VCPan/my.domain.com/some/image/url.jpg',
                                'opts': {'center': [50, 0],
                                         'height': 50,
                                         'original_height': 100,
                                         'original_width': 100,
                                         'width': 50}},
    'no_opts': {'new': '/964rCTkAEDtvjy_a572k7kRa0SU=/my.domain.com/some/image/url.jpg',
                'old': '/CDxCJT0ZmRlFAnX4cSpdkvVM9cB4m8sk2UUHOaYGy6_lXXGXm2Ux9PV6we7enK02/my.domain.com/some/image/url.jpg',
                'opts': {}},
    'trim_direction_and_tolerance_param': {'new': '/TUCEIhtWfI1Uv9zjavCSl_i0A_8=/trim:bottom-right:15/my.domain.com/some/image/url.jpg',
                                           'old': '/4NpyAbO5ftYI0cSARMwQDI_pXkIQvVbYRmemn3fV-gj7BdxHgb_SOjdwCfBv_ri6MmF4M4mWJlG5Wo4jFcLYhA==/my.domain.com/some/image/url.jpg',
                                           'opts': {'trim': [u'bottom-right',
                                                             15]}},
    'trim_direction_param': {'new': '/kXPwSmqEvPFQezgzBCv9BtPWmBY=/trim:bottom-right/my.domain.com/some/image/url.jpg',
                             'old': '/4NpyAbO5ftYI0cSARMwQDLqp2YYbtWnDQjl7RWpZTiES6eY7AokKR8MxWv-SG1MITsAJ-HZkU5sksimly3NCpA==/my.domain.com/some/image/url.jpg',
                             'opts': {'trim': [u'bottom-right']}},
    'trim_no_param': {'new': '/w23BC0dUiYBFrUnuoYJe8XROuyw=/trim/my.domain.com/some/image/url.jpg',
                      'old': '/6L3Y85hEwKgarH4vVUYqpvsF3EeBv9I6N3AJ8G_-uLoyYXgziZYmUblajiMVwtiE/my.domain.com/some/image/url.jpg',
                      'opts': {'trim': True}},
    'trim_smart': {'new': '/qvDxNvUzB-0805ufJrLaFNdz2R0=/trim/smart/my.domain.com/some/image/url.jpg',
                   'old': '/9-9ZKCZbWCqVjfTtv6y2jsmzdehd-TzMVoCIli0mkti-2rHfaNX4I-Z1FVBBN1XE/my.domain.com/some/image/url.jpg',
                   'opts': {'smart': True, 'trim': True}},
    'valign_halign': {'new': '/xcKQX02B7vTRHHuDWF3h4l7Rb0k=/middle/top/my.domain.com/some/image/url.jpg',
                      'old': '/4bfvkEahEVjbfYZUZjTHO8mzdehd-TzMVoCIli0mkti-2rHfaNX4I-Z1FVBBN1XE/my.domain.com/some/image/url.jpg',
                      'opts': {'halign': 'middle', 'valign': 'top'}},
    'valign_middle': {'new': '/964rCTkAEDtvjy_a572k7kRa0SU=/my.domain.com/some/image/url.jpg',
                      'old': '/CDxCJT0ZmRlFAnX4cSpdkvVM9cB4m8sk2UUHOaYGy6_lXXGXm2Ux9PV6we7enK02/my.domain.com/some/image/url.jpg',
                      'opts': {'valign': 'middle'}},
    'valign_top': {'new': '/1QQo5ihObuhgwl95--Z3g78vjiE=/top/my.domain.com/some/image/url.jpg',
                   'old': '/Wnwv6HPE1C2KwNbHZv7kk6gkXX8ssFdGRUM4KjiysBVio7iZIdaIcxAG1lJAGM2V/my.domain.com/some/image/url.jpg',
                   'opts': {'valign': 'top'}},
    'vertical_crop_with_actual_center': {'new': '/JLH65vJTu6d-cXBmqe5hYoSD4ho=/10x0:90x100/40x50/my.domain.com/some/image/url.jpg',
                                         'old': '/BbIn4e2Hf5tN7Mn4uG09eEkKXlHMWVG2Hvgmx9qpSB0S6eY7AokKR8MxWv-SG1MITsAJ-HZkU5sksimly3NCpA==/my.domain.com/some/image/url.jpg',
                                         'opts': {'center': [50, 50],
                                                  'height': 50,
                                                  'original_height': 100,
                                                  'original_width': 100,
                                                  'width': 40}},
    'vertical_crop_with_bottom_center': {'new': '/JLH65vJTu6d-cXBmqe5hYoSD4ho=/10x0:90x100/40x50/my.domain.com/some/image/url.jpg',
                                         'old': '/BbIn4e2Hf5tN7Mn4uG09eEkKXlHMWVG2Hvgmx9qpSB0S6eY7AokKR8MxWv-SG1MITsAJ-HZkU5sksimly3NCpA==/my.domain.com/some/image/url.jpg',
                                         'opts': {'center': [50, 100],
                                                  'height': 50,
                                                  'original_height': 100,
                                                  'original_width': 100,
                                                  'width': 40}},
    'vertical_crop_with_top_center': {'new': '/JLH65vJTu6d-cXBmqe5hYoSD4ho=/10x0:90x100/40x50/my.domain.com/some/image/url.jpg',
                                      'old': '/BbIn4e2Hf5tN7Mn4uG09eEkKXlHMWVG2Hvgmx9qpSB0S6eY7AokKR8MxWv-SG1MITsAJ-HZkU5sksimly3NCpA==/my.domain.com/some/image/url.jpg',
                                      'opts': {'center': [50, 0],
                                               'height': 50,
                                               'original_height': 100,
                                               'original_width': 100,
                                               'width': 40}},
    'width': {'new': '/eFwrBWryxtRw9hDSbQPhi5iLpo8=/300x0/my.domain.com/some/image/url.jpg',
              'old': '/u4dSJTO5jjEX-MKV1bkPtYKzqfXvHPpTEZzYBP1EbLnynvgyyWmcybNEl-5VCPan/my.domain.com/some/image/url.jpg',
              'opts': {'width': 300}},
    'width_height': {'new': '/TrM0qqfcivb6VxS3Hxlxn43W21k=/200x300/my.domain.com/some/image/url.jpg',
                     'old': '/uh22Apy07feFDryKeol0A9mpOfX6dPXw4vP4kJU-jTfyF6y1GJBJyp7CHYh1H3R2/my.domain.com/some/image/url.jpg',
                     'opts': {'height': 300, 'width': 200}},
    'width_height_fit_in': {'new': '/LOv6ArMOJA2VRpfMQjjs4xSyZpM=/fit-in/200x300/my.domain.com/some/image/url.jpg',
                            'old': '/oR1Jf4CTppv9gQFGDy2Vp4RsYt933npxRp6FA2qKWw07sGap3zmi3qkD8jw2tIqf/my.domain.com/some/image/url.jpg',
                            'opts': {'fit_in': True,
                                     'height': 300,
                                     'width': 200}},
    'width_height_smart': {'new': '/hdzhxXzK45DzNTru5urV6x6xxSs=/200x300/smart/my.domain.com/some/image/url.jpg',
                           'old': '/PNJk8bzmI2JEbFxGeyj1YObecJsOgxj2By9YEA3z0_nulwD9agDYAva1QlFRSyex/my.domain.com/some/image/url.jpg',
                           'opts': {'height': 300, 'smart': True, 'width': 200}}
}
